### PR TITLE
Create notifi card phone inputs

### PR DESCRIPTION
**Pull request by Nathan-Notifi**
Updates phone input handle country codes.

Phone Input

### CODE REVIEW

**Comment by kargo-k** [comment]
no telegram?

styling nits -- 
1. smaller logo
2. more padding
3. text alignment
4. size of the card is a little weird

have you seen the figma?  https://www.figma.com/file/8A6HBoozhXpR7S48QrDysu/Notifi?node-id=694%3A5744

**Comment by Nathan-Notifi** [comment]
Ooo I've seen the prototype but having this helps!

**Comment by nimeshamin** [comment]
@Nathan-Notifi did we add the Telegram support yet?

**Comment by Nathan-Notifi** [comment]
@nimesh-notifi i saw that there was a flag for it called `telegram enabled`. Was this hooked up previously?

The demo doesn't show it because the flag was on.

**Pull request closed without merging**
